// Static, read-only workflow: no capture, wallet interaction or payment starts here.
const APP = "https://delta-witness-app.pages.dev/";
const LEGACY_PROOF_ID = "56347db8-1aa5-447f-a0e4-3bb052d7aa89";
function esc(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;");
}
const css = "*{box-sizing:border-box}body{margin:0;background:#faf9f6;color:#14243a;font:17px/1.6 system-ui,sans-serif}header,main,footer{max-width:1080px;margin:auto;padding:24px}header{display:flex;justify-content:space-between;gap:20px;align-items:center;border-bottom:1px solid #d4d9df}nav{display:flex;flex-wrap:wrap;gap:20px}a{color:#0759a9;text-underline-offset:3px}a:focus-visible,summary:focus-visible{outline:3px solid #0759a9;outline-offset:5px}.brand{font-weight:800;letter-spacing:.08em;color:#14243a}.eyebrow{font-size:13px;letter-spacing:.09em;text-transform:uppercase;color:#455c70}.hero{padding:50px 0 36px;max-width:830px}h1{font-size:clamp(34px,5vw,58px);line-height:1.08;letter-spacing:-.035em;margin:16px 0 24px}h2{font-size:28px;line-height:1.2;margin-top:0}h3{font-size:21px;line-height:1.3;margin:8px 0 12px}p{max-width:76ch}.lead{font-size:21px;line-height:1.5}.actions{display:flex;flex-wrap:wrap;gap:12px;align-items:center;margin:26px 0 12px}.button{display:inline-block;border:1px solid #164c3c;border-radius:8px;background:#164c3c;color:#fff;padding:12px 18px;font-weight:650;text-decoration:none}.button.secondary{background:transparent;color:#164c3c}.note{font-size:14px;color:#46576a}.section{padding:36px 0;border-top:1px solid #d4d9df}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.card{background:#fff;border:1px solid #ccd4dc;padding:24px;border-radius:12px}.step{display:block;font-size:13px;font-weight:700;color:#526679;letter-spacing:.06em;text-transform:uppercase}.boundary{background:#eaf1f4;border:1px solid #beced9;border-radius:10px;padding:20px 24px;margin:24px 0}.price{font-size:28px;font-weight:750;line-height:1.2}.literal{font-family:ui-monospace,monospace;background:#f1f3f5;padding:14px;display:block}pre{padding:20px;overflow-x:auto;background:#14243a;color:#f5f8fc;border-radius:10px;font:14px/1.6 ui-monospace,monospace}code{overflow-wrap:anywhere}li{margin:10px 0}.badge{display:inline-block;font-size:12px;font-weight:750;letter-spacing:.08em;padding:5px 9px;background:#eee5cd;color:#5a440f;border-radius:4px}details{border-top:1px solid #ccd4dc;padding:18px 0}summary{cursor:pointer;font-weight:700}footer{font-size:14px;color:#46576a;border-top:1px solid #d4d9df}@media(max-width:720px){header{align-items:flex-start;flex-direction:column}header,main,footer{padding:20px}.hero{padding-top:30px}.grid{grid-template-columns:1fr}.card{padding:20px}h2{font-size:25px}.lead{font-size:19px}}";
function frame(origin: string, title: string, description: string, path: string, body: string): string {
  return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>' + esc(title) + '</title><meta name="description" content="' + esc(description) + '"><link rel="canonical" href="' + esc(origin) + path + '"><link rel="icon" href="/favicon.ico"><style>' + css + '</style></head><body><header><a class="brand" href="/">DELTA WITNESS</a><nav aria-label="Main navigation"><a href="/#supplier-example">Supplier example</a><a href="/docs">API guide</a><a href="' + APP + '">Open buyer app</a></nav></header><main>' + body + '</main><footer>Public web observations · Base mainnet USDC · HTTP JSON API with x402<br>DELTA records what its capture system observed. It does not verify supplier claims or authorize an order.</footer></body></html>';
}
function prices(): string {
  return '<div class="grid"><article class="card"><span class="step">Start with one source</span><h3>Capture</h3><p class="price">1 USDC</p><p>One public page observation. Receive a timestamp, content hashes and proof references.</p><a href="' + APP + '?product=capture">Review a Capture request</a></article><article class="card"><span class="step">Check an explicit condition</span><h3>Preflight</h3><p class="price">5 USDC</p><p>One fresh observation compared with prior hashes or literal text rules you supply.</p><a href="' + APP + '?product=preflight">Review a Preflight request</a></article><article class="card"><span class="step">API evidence package</span><h3>Guarded-Action Pilot</h3><p class="price">10 USDC</p><p>1–3 public HTTPS pages and one optional deterministic check. It does not perform an order or other downstream action.</p><a href="/docs#pilot">See the Pilot request</a></article></div><p class="note">Per request, paid in USDC on Base mainnet. No subscription. Opening a link does not make a payment. Review the current quote and authorize payment in your own wallet.</p>';
}
export function conversionLandingHtml(origin: string, version: string): string {
  const base = esc(origin);
  const body = [
    '<section class="hero"><p class="eyebrow">For sourcing workflows that need a source record · v' + esc(version) + '</p><h1>Keep a record of the page behind your supplier recommendation.</h1><p class="lead">When a decision depends on a public supplier page, DELTA can capture that page and return a timestamp, content hashes and a proof reference to keep beside the recommendation.</p><div class="actions"><a class="button" href="#supplier-example">See the supplier workflow</a><a class="button secondary" href="' + APP + '?product=capture">Review a 1 USDC Capture</a></div><p class="note">Public pages only. The public proof contains metadata and hashes; original text and screenshots are private and are not available to reviewers through this link.</p></section>',
    '<section class="section" id="supplier-example" aria-labelledby="example-heading"><span class="badge">FICTIONAL SCENARIO · NO PAYMENT</span><h2 id="example-heading">A recommendation should have a source record beside it.</h2><p>This is an illustrative workflow. No live capture or payment has been made for this supplier example.</p><div class="grid"><article class="card"><span class="step">01 · Decision context</span><h3>A lead-time claim matters</h3><p>A fictional supplier page says:</p><span class="literal">Lead time: 7 days</span><p>Your sourcing workflow uses that statement when recommending a supplier.</p></article><article class="card"><span class="step">02 · Capture at your checkpoint</span><h3>Record the public source</h3><p>Submit the public page URL to Capture. Store the returned proof reference with your own decision ID and rationale.</p><p class="note">No invented timestamp, hash, receipt or verdict is shown here.</p></article><article class="card"><span class="step">03 · Customer review</span><h3>Identify the observation you used</h3><p>If the fictional page later says <strong>14 days</strong>, the saved reference identifies the earlier DELTA observation and its hashes.</p><p class="note">The public verifier cannot show the original “7 days” text. Keep any authorized source material your reviewer needs separately.</p></article></div><div class="boundary"><h3>What can the reviewer actually inspect?</h3><p>The proof URL exposes source metadata, application-recorded capture times, artifact hashes and a manifest-integrity status. Capture times are not independently anchored. It does not expose captured HTML, Markdown or screenshots, independently attest when the decision happened, or verify that a supplier statement is true.</p><p>If your customer needs the original captured page, the current DELTA public proof is not a complete review package.</p></div></section>',
    '<section class="section"><h2>Inspect an existing proof before paying</h2><p>The available historical example captured <strong>example.com</strong>, not a supplier. Its integrity status is <code>legacy_unverifiable</code> and its attestation is <code>not_anchored</code>. It demonstrates the public metadata format; it is not customer adoption or current-format verification evidence.</p><div class="actions"><a class="button secondary" href="' + base + '/p/' + LEGACY_PROOF_ID + '">Open the historical proof</a><a href="' + base + '/v1/proofs/' + LEGACY_PROOF_ID + '">Read its JSON</a></div></section>',
    '<section class="section"><h2>Choose the smallest check that answers your question</h2>' + prices() + '</section>',
    '<section class="section"><h2>Before you use DELTA</h2><details><summary>Do I need Capture or Preflight?</summary><p>Use Capture to record an observation. Use Preflight only when you have explicit expected text, expected hashes or a prior DELTA proof to compare. A matching condition is not an approval to purchase.</p></details><details><summary>Will it read my logged-in supplier portal?</summary><p>No. DELTA captures public pages in its own browser. It does not inherit your login, cookies, shopping cart or negotiated terms.</p></details><details><summary>What does “verified” mean?</summary><p>For current-format proofs, it means the manifest bundle-root hash is internally consistent. It is not an independent timestamp, supplier endorsement, signature, or guarantee of legal admissibility.</p></details><details><summary>Can my agent call it?</summary><p>Use the HTTP JSON API with an x402-capable client. Read the <a href="/docs">API guide</a> for the no-payment first step, response handling and retry limitations.</p></details></section>'
  ].join("\n");
  return frame(origin, "DELTA Witness — Record the source behind a supplier decision", "Keep a timestamped public-page observation beside a supplier recommendation. Capture starts at 1 USDC on Base.", "/", body);
}
export function conversionDocsHtml(origin: string): string {
  const base = esc(origin);
  const body = [
    '<section class="hero"><p class="eyebrow">First request</p><h1>Start with one public page.</h1><p class="lead">Capture costs 1 USDC and returns a record of a DELTA observation. First inspect the free quote and historical example. Payment and live capture are separate steps.</p><div class="actions"><a class="button" href="' + APP + '?product=capture">Review a Capture request</a><a class="button secondary" href="#free-check">Inspect without paying</a></div><p class="note">The buyer app requires a Base-compatible injected wallet and Base USDC. It supports Capture and Preflight. The Pilot is an API flow.</p></section>',
    '<section class="section" id="free-check"><h2>1. Inspect without paying</h2><pre>curl "' + base + '/v1/quote?product=capture"\ncurl "' + base + '/v1/demo"</pre><p>These are read-only GET requests. The current historical example has <code>legacy_unverifiable</code> integrity and <code>not_anchored</code> attestation. It shows the output format, not a completed request of your own.</p><p>You can also inspect an unsigned challenge. An HTTP 402 response is expected here; no capture has run:</p><pre>curl -i "' + base + '/v1/capture" \\\n  -H "content-type: application/json" \\\n  -d &#39;{"url":"https://example.com/"}&#39;</pre><p class="note">A successful challenge is not paid-client compatibility. A real buyer flow also needs wallet authorization, settlement and completed delivery.</p></section>',
    '<section class="section"><h2>2. Choose a public source and review the quote</h2><p>Use a URL that is public without a login. Do not submit credentials, session tokens, private portal links or personal data in URL parameters. DELTA does not share your current browser session.</p>' + prices() + '<p>Your x402 client must validate the selected product, exact amount, Base network, canonical USDC asset and DELTA recipient before signing. A Capture-only approval must not become a Preflight or Pilot payment.</p><details><summary>Payment identifiers for integration review</summary><ul><li>Network: Base mainnet · eip155:8453</li><li>Canonical USDC: <code>0x833589fcd6edb6e08f4c7c32d4f71b54bda02913</code></li><li>DELTA recipient: <code>0x1990e21bc219696ff7fbc26527dbaed335ac6367</code></li><li>Exact raw amounts: Capture 1000000 · Preflight 5000000 · Pilot 10000000</li></ul><p>Do not make a standalone transfer to the recipient. It does not identify your request or establish delivery.</p></details></section>',
    '<section class="section"><h2>3. Keep the delivered record beside the decision</h2><p>A completed Capture returns <code>ok: true</code>, <code>proof_id</code>, <code>public_proof_url</code>, <code>manifest_url</code>, <code>bundle_root</code> and <code>observed_at</code>. Save the response with your own decision ID, source URL and rationale. Keep the settlement evidence from your payment client separately.</p><div class="boundary"><h3>Metadata is not the original page</h3><p>The public proof exposes metadata and hashes only. Raw HTML, Markdown and screenshots remain private; no buyer download is provided by these public endpoints. A timestamp is recorded by the DELTA application, not independently anchored. Manifest integrity does not certify source truth.</p></div><p>Count delivery only when the response is a completed result with the expected proof fields. HTTP success alone is insufficient:</p><ul><li><strong>402:</strong> payment requirements, not a completed observation</li><li><strong>202 / processing:</strong> still processing, not delivered</li><li><strong>502 / retryable_failure:</strong> capture failed after the paid flow; resolve payment and delivery state before another authorization</li><li><strong>Timeout or malformed response:</strong> outcome unknown; do not blindly make a fresh payment</li></ul><p>Idempotent replay requires the identical payment header and matching normalized request. Retain the original request/payment context. A newly signed payment may be a different paid request.</p></section>',
    '<section class="section" id="preflight"><h2>Optional: check a literal condition</h2><p>Public Preflight costs 5 USDC. This is a request-shape example, not a live supplier result. Replace the illustrative URL and text with an authorized public source and your actual condition.</p><pre>POST /v1/preflight\ncontent-type: application/json\n\n{\n  "url": "https://example.com/",\n  "expected": {\n    "contains": ["Example Domain"],\n    "excludes": ["Final sale"]\n  }\n}</pre><p>Text checks are case-sensitive substring matches on captured Markdown. You can also compare expected hashes or a prior DELTA proof for the same URL. Inspect <code>safe</code>, <code>changed</code>, <code>reason</code> and <code>diff</code>; <code>safe: true</code> means your deterministic checks matched. With no comparison criteria, the result is unknown. DELTA does not authorize or execute the downstream action.</p></section>',
    '<section class="section" id="pilot"><h2>Optional: package up to three sources</h2><p>The Guarded-Action Pilot costs 10 USDC for 1–3 public HTTPS URLs and at most one optional deterministic preflight. It returns separate proof references. It does not purchase, submit, or enforce a decision.</p><p>Use the <a href="' + base + '/openapi.json">OpenAPI schema</a> for the exact Pilot input. This guide does not claim a verified paid integration or that current SDKs expose a Pilot method.</p></section>',
    '<section class="section"><h2>Integration references</h2><ul><li><a href="https://github.com/15998194110/delta-witness/tree/master/packages/js-client">JavaScript client</a>: paid methods require your own approved x402-capable fetch</li><li><a href="' + base + '/openapi.json">OpenAPI 3.1</a> · <a href="' + base + '/SKILL.md">Agent skill</a> · <a href="' + base + '/postman.json">Postman collection</a></li><li>Authenticated partner Capture, partner Preflight and each new Watch check cost 1 USDC under their separate prepaid partner flow. They are not the public Preflight route.</li></ul></section>'
  ].join("\n");
  return frame(origin, "DELTA Witness — First Capture and API guide", "Inspect a free quote and historical proof, choose a public URL, and understand paid Capture and Preflight responses.", "/docs", body);
}

